version: '3'
services:
  influxdb:
    image: 'bitnami/influxdb:latest'
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER_PASSWORD=password123
      - INFLUXDB_USER=my_user
      - INFLUXDB_USER_PASSWORD=my_password
      - INFLUXDB_DB=my_database
    networks:
      - influx-network
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - C:/Users/Andreas/Documents/GitHub/timeseries-data/influxdb:/bitnami/influxdb

  grafana:
    image: 'grafana/grafana:5.1.0'
    ports:
      - 3000:3000
    networks:
      - influx-network

networks:
  influx-network:
    driver: bridge
